name: Deploy Storybook To GitHub Pages

on:
  workflow_dispatch:
jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Storybook page
        run: |
          yarn build-storybook
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
